name: normal

on:
    push:
        branches: [ master, zig-nightly ]
    pull_request:
        branches: [ master, zig-nightly ]

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  submodules: true

            - name: Get Zig
              uses: goto-bus-stop/setup-zig@v1
              with:
                  version: '0.7.1' 
              if: ${{ github.ref == 'refs/heads/master' }}

            - name: Get Nightly Zig
              uses: goto-bus-stop/setup-zig@v1
              with:
                  version: 'master'
              if: ${{ github.ref == 'refs/heads/zig-nightly' }}

            - name: Install Packages
              run: sudo apt-get install grub-pc-bin

            - name: Build ISO Image
              run: make

            - name: Run Unit Tests
              run: make test
